// <auto-generated />
using System;
using AngularMusicApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AngularMusicApp.Migrations
{
    [DbContext(typeof(AngularMusicAppContext))]
    [Migration("20210414182757_Add_Data_To_MusicTable")]
    partial class Add_Data_To_MusicTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AngularMusicApp.Models.Song", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Composer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Song");

                    b.HasData(
                        new
                        {
                            ID = new Guid("551e9dab-b73e-4322-8200-bfab4a214d9f"),
                            Composer = "Whisnants",
                            Name = "I'll Live in Glory",
                            Year = 2007
                        },
                        new
                        {
                            ID = new Guid("d20287c1-f990-46d2-9698-6897f81e23e0"),
                            Composer = "Casting Crowns",
                            Name = "East to West",
                            Year = 2010
                        },
                        new
                        {
                            ID = new Guid("5dcca768-86e0-4745-a93d-9f2e268a75c1"),
                            Composer = "Kutless",
                            Name = "What Faith Can Do",
                            Year = 2009
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
